- name: Deploy Node-js app
  hosts: all
  become: true
  vars:
    nodejs_v: 18
  tasks:
    - name: Update and Upgrade packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
    - name: Install Dependencies
      apt:
        pkg:
          - curl
          - rsync
          - nginx
          - supervisor
        state: present
      tags: install
    - name: Update npm globally
      npm:
        global: yes
        name: "{{ item }}"
        state: latest
      with_items:
        - npm
    - name: Set up application directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/projects/roadtok8s/js/src/
        - /var/log/supervisor/roadtok8s/js/
    - name: Copy Node.js source to remote server
      synchronize:
        src: "{{ playbook_dir }}/../../src/"
        dest: /opt/projects/roadtok8s/js/
        recursive: yes
        delete: yes
    - name: Copy package to remove server
      synchronize:
        src: "{{ playbook_dir }}/../../package.json"
        dest: /opt/projects/roadtok8s/js/
        recursive: yes
        delete: yes
    - name: Install Node.js Packages
      shell: |
        npm install
      args:
        executable: /bin/bash
        chdir: "/opt/projects/roadtok8s/js"
      notify: reload supervisor
    - name: Configure node.js with supervisor
      copy:
        src: ../conf/supervisor.conf
        dest: /etc/supervisor/conf.d/roadtok8s-js.conf
      notify: reload supervisor
    - name: Configure Nginx with supervisor
      copy:
        src: ../conf/nginx.conf
        dest: /etc/nginx/sites-available/roadtok8s-js
      notify: reload nginx
    - name: Enable Nginx site
      command: ln -s /etc/nginx/sites-available/roadtok8s-js /etc/nginx/sites-enabled
      args:
        creates: /etc/nginx/sites-enabled/roadtok8s-js
    - name: Remove Nginx default site
      file:
        path: "{{ item }}"
        state: absent
      notify: restart nginx
      with_items:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default

  handlers:
    - name: restart supervisor
      command: "{{item}}"
      with_items:
        - supervisorctl reread
        - supervisorctl update
        - supervisorctl restart roadtok8s-js
      notify: restart nginx
    - name: restart nginx
      services:
        name: nginx
        status: restarted
        enabled: yes
      
