name: Build & Push Container
on:
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DH_USER: "${{ secrets.DOCKERHUB_USER }}"
      REPO: "${{ secrets.DOCKERHUB_REPO }}"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6.0.0
      with:
          node-version: "18"
    - uses: docker/login-action@v3.6.0
      with: 
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PAT }}"
    - name: Build Container
      run: |
          docker build -f dockerfile \
            -t "$DH_USER/$REPO:latest" \
            -t "$DH_USER/$REPO:${{ github.sha }}" \
            .
    - name: Push Container
      run: |
          docker push "$DH_USER/$REPO" --all-tags
